"use client";

import { motion, useReducedMotion } from "framer-motion";
import {
  Activity,
  Bot,
  CheckCircle2,
  Clock3,
  Copy,
  LoaderCircle,
  RefreshCw,
  Sparkles,
  Tags,
} from "lucide-react";

import {
  AIBadge,
  CardContent,
  CardHeader,
  CardTitle,
  CardWrapper,
  PageSection,
  StatusBadge,
} from "@/components/shared";
import { Button } from "@/components/ui/button";
import type { AIAnalysis } from "@/types";

type ConversationAIPanelProps = {
  analysis: AIAnalysis;
  isAnalyzing: boolean;
  latencyMs?: number | null;
  error: string | null;
  onAnalyze: () => void;
};

function sentimentTone(sentiment: AIAnalysis["sentiment"]) {
  if (sentiment === "Positive") return "success" as const;
  if (sentiment === "Neutral") return "neutral" as const;
  if (sentiment === "Concerned") return "warning" as const;
  return "danger" as const;
}

export function ConversationAIPanel({
  analysis,
  isAnalyzing,
  latencyMs,
  error,
  onAnalyze,
}: ConversationAIPanelProps) {
  const reduceMotion = useReducedMotion();
  const providerIsMock =
    analysis.source === "mock" || analysis.source === "fallback";

  return (
    <PageSection
      title="Conversation Intelligence"
      description="Live structured understanding, response guidance, and operational signals."
      action={
        <Button
          size="lg"
          onClick={onAnalyze}
          disabled={isAnalyzing}
          aria-describedby="analysis-provider-message"
        >
          {isAnalyzing ? (
            <LoaderCircle className="size-4 animate-spin" aria-hidden />
          ) : (
            <Sparkles className="size-4" aria-hidden />
          )}
          {isAnalyzing ? "Analyzing…" : "Analyze with AI"}
        </Button>
      }
    >
      <div aria-live="polite">
        {error ? (
          <div
            className="border-telosa-red/20 bg-telosa-red-muted text-telosa-red mb-4 flex flex-col gap-3 rounded-lg border p-3 text-sm sm:flex-row sm:items-center sm:justify-between"
            role="alert"
          >
            <span>{error}</span>
            <Button variant="outline" size="sm" onClick={onAnalyze}>
              <RefreshCw className="size-3.5" aria-hidden />
              Retry
            </Button>
          </div>
        ) : null}

        <div
          id="analysis-provider-message"
          className={
            providerIsMock
              ? "border-telosa-purple/20 bg-telosa-purple-muted text-telosa-purple mb-4 rounded-xl border px-3.5 py-2.5 text-xs"
              : "border-telosa-green/20 bg-telosa-green-muted text-telosa-green mb-4 rounded-xl border px-3.5 py-2.5 text-xs"
          }
        >
          {analysis.source === "fallback"
            ? "Gemini was unavailable. A reliable mock analysis is shown instead."
            : analysis.source === "mock"
              ? "Mock AI provider is active. Set USE_REAL_AI=true to use Gemini."
              : "Analysis generated by Gemini using structured JSON output."}
        </div>
      </div>

      <motion.div
        key={`${analysis.source}-${analysis.summary}-${analysis.confidence}`}
        initial={reduceMotion ? false : { opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.25 }}
        className="space-y-5"
      >
        <CardWrapper className="from-telosa-purple-muted/70 via-card to-telosa-blue-muted/50 border-telosa-purple/15 bg-gradient-to-br">
          <CardContent className="grid gap-5 pt-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center">
            <div className="space-y-3">
              <div className="flex flex-wrap items-center gap-2">
                <AIBadge
                  label={
                    analysis.source === "gemini"
                      ? "Provider · Gemini"
                      : analysis.source === "fallback"
                        ? "Provider · Fallback"
                        : "Provider · Mock"
                  }
                />
                <StatusBadge
                  label={analysis.source === "gemini" ? "Live" : "Protected"}
                  tone={analysis.source === "gemini" ? "success" : "warning"}
                />
              </div>
              <div className="text-muted-foreground flex items-center gap-2 text-xs">
                <Activity className="text-telosa-purple size-4" aria-hidden />
                Structured analysis is ready for executive review.
              </div>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <div
                className="relative flex size-16 items-center justify-center rounded-full"
                style={{
                  background: `conic-gradient(var(--telosa-purple) ${analysis.confidence}%, var(--muted) 0)`,
                }}
                role="progressbar"
                aria-label="AI confidence"
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={analysis.confidence}
              >
                <div className="bg-card flex size-12 items-center justify-center rounded-full shadow-inner">
                  <span className="text-xs font-semibold tabular-nums">
                    {analysis.confidence}%
                  </span>
                </div>
              </div>
              <div className="border-border/70 bg-background/45 flex min-w-32 items-center gap-3 rounded-xl border p-3 shadow-sm">
                <div className="bg-telosa-blue-muted text-telosa-blue flex size-9 items-center justify-center rounded-lg">
                  <Clock3 className="size-4" aria-hidden />
                </div>
                <div>
                  <p className="text-muted-foreground text-[10px] font-semibold tracking-wide uppercase">
                    Latency
                  </p>
                  <p className="text-sm font-semibold tabular-nums">
                    {latencyMs === null || latencyMs === undefined
                      ? "Ready"
                      : latencyMs >= 1000
                        ? `${(latencyMs / 1000).toFixed(1)}s`
                        : `${latencyMs}ms`}
                  </p>
                </div>
              </div>
            </div>
          </CardContent>
        </CardWrapper>

        <div className="grid gap-4 sm:grid-cols-2">
          <IntelligenceField
            icon={Bot}
            label="Intent"
            value={analysis.intent}
          />
          <CardWrapper>
            <CardContent className="space-y-2 pt-5">
              <p className="text-muted-foreground text-xs font-medium">
                Sentiment
              </p>
              <StatusBadge
                label={analysis.sentiment}
                tone={sentimentTone(analysis.sentiment)}
              />
            </CardContent>
          </CardWrapper>
        </div>

        <CardWrapper>
          <CardHeader className="pb-2">
            <div className="flex items-center gap-2">
              <Tags className="text-telosa-purple size-4" aria-hidden />
              <CardTitle className="text-sm">Extracted entities</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            {analysis.entities.length > 0 ? (
              <div className="flex flex-wrap gap-2">
                {analysis.entities.map((entity, index) => (
                  <span
                    key={`${entity.type}-${entity.value}-${index}`}
                    className="border-border bg-muted/60 rounded-full border px-2.5 py-1 text-xs"
                  >
                    <span className="text-muted-foreground">
                      {entity.type}:{" "}
                    </span>
                    <span className="font-medium">{entity.value}</span>
                  </span>
                ))}
              </div>
            ) : (
              <p className="text-muted-foreground text-sm">
                No entities detected.
              </p>
            )}
          </CardContent>
        </CardWrapper>

        <CardWrapper className="border-telosa-purple/15 bg-telosa-purple-muted/20 overflow-hidden">
          <CardHeader className="flex flex-row items-center justify-between gap-3 pb-2">
            <CardTitle className="text-sm">AI Summary</CardTitle>
            <AIBadge label="AI Summary" />
          </CardHeader>
          <CardContent>
            <p className="text-[0.9375rem] leading-7">{analysis.summary}</p>
          </CardContent>
        </CardWrapper>

        <CardWrapper className="border-telosa-green/15 bg-telosa-green-muted/10">
          <CardHeader className="flex flex-row items-center justify-between gap-3 pb-2">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="text-telosa-green size-4" aria-hidden />
              <CardTitle className="text-sm">Suggested reply</CardTitle>
            </div>
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Copy suggested reply"
              onClick={() =>
                void navigator.clipboard?.writeText(analysis.suggestedReply)
              }
            >
              <Copy className="size-3.5" />
            </Button>
          </CardHeader>
          <CardContent>
            <p className="text-[0.9375rem] leading-7">
              {analysis.suggestedReply}
            </p>
          </CardContent>
        </CardWrapper>

        <div className="grid gap-3 sm:grid-cols-2">
          <DetectionState
            label="Duplicate detection"
            detected={analysis.isDuplicate}
            detail={
              analysis.duplicateOfId
                ? `Related to ${analysis.duplicateOfId}`
                : undefined
            }
          />
          <DetectionState label="Spam detection" detected={analysis.isSpam} />
        </div>
      </motion.div>
    </PageSection>
  );
}

type IntelligenceFieldProps = {
  icon: typeof Bot;
  label: string;
  value: string;
};

function IntelligenceField({
  icon: Icon,
  label,
  value,
}: IntelligenceFieldProps) {
  return (
    <CardWrapper>
      <CardContent className="space-y-2 pt-5">
        <div className="text-muted-foreground flex items-center gap-2 text-xs font-medium">
          <Icon className="size-4" aria-hidden />
          {label}
        </div>
        <p className="text-sm font-semibold">{value}</p>
      </CardContent>
    </CardWrapper>
  );
}

function DetectionState({
  label,
  detected,
  detail,
}: {
  label: string;
  detected: boolean;
  detail?: string;
}) {
  return (
    <CardWrapper>
      <CardContent className="flex items-center justify-between gap-3 pt-5">
        <div>
          <p className="text-sm font-medium">{label}</p>
          {detail ? (
            <p className="text-muted-foreground mt-0.5 text-xs">{detail}</p>
          ) : null}
        </div>
        <StatusBadge
          label={detected ? "Detected" : "Clear"}
          tone={detected ? "warning" : "success"}
        />
      </CardContent>
    </CardWrapper>
  );
}
